blank_issues_enabled: false
contact_links:
  - name: SwitchBot (Official website)
    url: https://www.switch-bot.com/
  - name: Facebook @SwitchBotRobot
    url: https://www.facebook.com/SwitchBotRobot/
  - name: Twitter @SwitchBot
    url: https://twitter.com/switchbot
